OnlineCourseApp/Controllers/CityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.ViewModels;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class CityController : NotificationsController
    {
        private ICityRepository cityRepository;
        private IRegionRepository regionRepository;
        public CityController(ICityRepository cityRepository, 
                                      IRegionRepository regionRepository)
        {
            this.cityRepository = cityRepository;
            this.regionRepository = regionRepository;
        }

        public IActionResult DodajForma()
        {
            ViewData["regije"] = regionRepository.GetAllRegions();
            CityVM Model = new CityVM();
            return PartialView(Model);

        }
        public IActionResult Dodaj(CityVM m)
        {
            City city = new City
            {
                Description = m.Description,
                RegionID = m.RegionID,
                ZipCode = m.ZipCode
            };
            cityRepository.Add(city);
            SuccessNotification = "Uspješno ste dodali grad.";

            return Redirect("/City/Prikaz");
        }

        public IActionResult Prikaz()
        {
            var m = cityRepository.GetAllCities();
            return View(m);
        }

        public IActionResult Obrisi(int cityID)
        {
            cityRepository.Delete(cityID);
            SuccessNotification = "Uspješno ste obrisali grad.";
            return Redirect(url: "/City/Prikaz");
        }
    }
}

OnlineCourseApp/Controllers/RegionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.RepositoryInterfaces;

namespace OnlineCourseApp.Controllers
{
    public class RegionController : NotificationsController
    {
        private IRegionRepository regionRepository;
        public RegionController(IRegionRepository regionRepository)
        { this.regionRepository = regionRepository; }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult DodajForma()
        {
            return PartialView();

        }

        [Authorize(Roles = "Admin")]
        public IActionResult Dodaj(string description)
        {
            var region = new Region
            {
                Description = description
            };
            regionRepository.Add(region);
            SuccessNotification = "Uspješno ste dodali regiju.";
            return Redirect("/Region/Prikaz");
        }

        [Authorize(Roles = "Admin,Profesor,Student")]
        public IActionResult Prikaz()
        {
            var regije = regionRepository.GetAllRegions();
            return View(regije);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Obrisi(int regionID)
        {
            regionRepository.Delete(regionID);
            SuccessNotification = "Uspješno ste obrisali regiju.";
            return Redirect(url: "/Region/Prikaz");
        }
    }
}

OnlineCourseApp/Views/City/DodajForma.cshtml
@model CityVM
@{
    var regije = (List<SelectListItem>)ViewData["regije"];
}

        <form asp-action="Dodaj" method="post" id="forma">
            <div class="modal-body">
                <input asp-for="CityID" style="display:none" />
                <div class="form-group">
                    <label>Naziv opštine</label>
                    <input asp-for="Description" class="form-control" name="Description" id="Opis" />
                    <span asp-validation-for="Description" class="text-danger"></span>

                </div>

                <div class="form-group">
                    <label>Regije</label>
                    <div style="display:flex">
                        <select asp-for="RegionID" asp-items="regije" class="form-control">
                            <option disabled>(Odaberite regiju)</option>
                        </select>
                        <a href="@Url.Action("Prikaz","Region")" class="cursor-pointer btn btn-primary" style="margin-left:1rem">+</a>
                    </div>
                        <span asp-validation-for="RegionID" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Poštanski broj</label>
                        <input asp-for="ZipCode" class="form-control" name="ZipCode" id="postanskiBroj" />
                        <span asp-validation-for="ZipCode" class="text-danger"></span>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zatvori</button>
                        <input type="submit" class="btn btn-primary" value="Sačuvaj" id="submit">
                    </div>
                </div>
        </form>

<style>
    .error {
        color: darkred;
        display: block;
    }
</style>

@section Scripts {
    @await Html.PartialAsync("/Views/Shared/_ValidationScriptsPartial.cshtml")
    <script>

        $(document).ready(function () {
            $("#forma").validate({
                rules: {
                    "Opis": {
                        required: true,
                        lettersonly: true
                    },
                    "postanskiBroj": {
                        required: true,
                        minlength: 3
                    }
                },
                messages: {
                    "Opis": {
                        required: 'Obavezno polje',
                        lettersonly: 'Unesite naziv regije'
                    },
                    "postanskiBroj": {
                        required: 'Obavezno polje',
                        minlength: 'Neispravan unos'
                    }
                }
            });
        });

        $("#submit").click(function () {
            if ($("#forma").valid())
                return true;
        });
    </script>
}

OnlineCourseApp/Views/City/Prikaz.cshtml
@model List<CityVM>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Settings")">Postavke</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Gradovi</span>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-3"></div>
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <button class="btn btn-primary btn-popup" data-container="body" data-modaltitle="Dodaj opštinu" data-url="@Url.Action("DodajForma","City")"><i class="fa fa-plus-circle"></i> Dodaj opštinu</button>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <table class="table table-striped table-bordered" style="background:white;">
            <thead>
                <tr>
                    <th scope="col">Naziv opštine</th>
                    <th scope="col">Regija</th>
                    <th scope="col">Poštanski broj</th>
                    <th scope="col">Akcija</th>
                </tr>
            </thead>
            <tbody>
                @foreach (CityVM x in Model)
                {
                    @if (x.Description != null)
                    {
                        <tr>
                            <td>  @x.Description </td>
                            <td>  @x.Region </td>
                            <td>  @x.ZipCode </td>
                            <td>
                                <a href="/City/Obrisi?cityID=@x.CityID" class="btn btn-outline-danger">Obriši</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>


@*<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-url="@Url.Action("DodajForma","City")" style="z-index: 1400;">
</div>*@


@*@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btn-popupp").click(function () {
                event.preventDefault();
                var url = $("#exampleModalCenter").data('url');
                jQuery.get(url, function (data) {

                    $("#exampleModalCenter").html(data);
                    $("#exampleModalCenter").modal('show');

                })
            })
        });
    </script>
}*@

<style>
    label {
        margin-bottom: 0px;
    }

    .container-fluid {
        padding: 15px;
        background: white;
        margin-bottom: 25px;
        border: 1px solid #dee2e6;
        border-radius: 10px;
    }

    .btn-popup {
        width: 100%;
    }
</style>