OnlineCourseApp/Controllers/ChoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class ChoiceController : NotificationsController
    {
        private IChoiceRepository choiceRepository;

        public ChoiceController(IChoiceRepository choiceRepository)
        {
            this.choiceRepository = choiceRepository;
        }

        public IActionResult Delete(int choiceID, int questionID, int examID)
        {
            choiceRepository.Delete(choiceID);
            SuccessNotification = "Uspješno ste obrisali odgovor.";

            return RedirectToAction("Details", "Question", new {  questionID,  examID });
        }

        public IActionResult Edit(int choiceID, int examID)
        {
            var choice = choiceRepository.EditChoice(choiceID, examID);

            if (choice == null)
            {
                ViewBag.ErrorMessage = "Odgovor nije pronađen.";
                return View("_NotFound");
            }

            choice.correctList.Add(new SelectListItem { Text = "Tačno", Value = "True" });
            choice.correctList.Add(new SelectListItem { Text = "Netačno", Value = "False" });

            return PartialView(choice);
        }

        public IActionResult SpremiIzmjene(ChoiceEditVM m)
        {
            var choice = choiceRepository.GetById(m.ChoiceID);
            if (choice == null)
            {
                ViewBag.ErrorMessage = "Odgovor nije pronađen.";
                return View("_NotFound");
            }
            else
            {
                
                choice.Text = m.Text;
                choice.Points = m.Points;
                choice.IsCorrect = m.IsCorrect;

                choiceRepository.Update(choice);
                SuccessNotification = "Uspješno ste ažurirali odgovor.";
            }

            return RedirectToAction("Details", "Question", new { questionID = m.QuestionID, examID = m.ExamID });
        }

    }
}

OnlineCourseApp/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineCourseApp.Enums;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace OnlineCourseApp.Controllers
{
    public class QuestionController : NotificationsController
    {
        private IQuestionRepository questionRepository;
        private IQuestionCategoryRepository _questionCategoryRepository;
        private IChoiceRepository choiceRepository;

        public QuestionController( IQuestionRepository questionRepository, IChoiceRepository choiceRepository, IQuestionCategoryRepository questionCategoryRepository)
        {
            this.questionRepository = questionRepository;
            this.choiceRepository = choiceRepository;
            _questionCategoryRepository = questionCategoryRepository;
        }

        [Authorize(Roles = "Admin, Profesor")]
        public IActionResult DodajForma(int examID)
        {
            ViewBag.ExamID = examID;
            QuestionAddVM model = new QuestionAddVM() { 
                QuestionCategory = new List<SelectListItem>(),
                QuestionType = new List<SelectListItem>()
            };
            model.QuestionCategory = questionRepository.GetQuestionCategories();

            model.QuestionType.Add(new SelectListItem { Text = "Više ponuđenih više tačnih", Value = ((int)QuestionType.MultipleChoice).ToString() });
            model.QuestionType.Add(new SelectListItem { Text = "Više ponuđenih jedno tačno", Value = ((int)QuestionType.Matching).ToString() });
            model.QuestionType.Add(new SelectListItem { Text = "Esej", Value = ((int)QuestionType.Essay).ToString() });

            return View(model);
        }

        [Authorize(Roles = "Admin, Profesor")]
        public IActionResult Dodaj(QuestionAddVM model, List<string> Answer, IFormCollection collection, List<string> Percentage)
        {

            if (!ModelState.IsValid)
            {
                return Redirect("/Question/DodajForma?examID=" + model.ExamID);
            }


            if (Answer.Count > 0 && Answer.Contains(null))
            {
                //error message
                ErrorNotification = "Unesite odgovore.";
                return Redirect("/Question/DodajForma?examID=" + model.ExamID);

            };

            var results = collection["checkboxes"];

            if (Answer.Count > 0 && results.Count == 0)
            {
                //error message
                ErrorNotification = "Označite tačne odgovore.";
                return Redirect("/Question/DodajForma?examID=" + model.ExamID);
            };

            Question question = new Question
            {
                QuestionCategoryID = model.QuestionCategoryID,
                QuestionType = (QuestionType)model.QuestionTypeID,
                ExamID = model.ExamID,
                QuestionNumber = questionRepository.GetLastQuestionNumber(model.ExamID) +1,
                Points = model.Points,
                IsActive =true,
                Text = model.Text
            };

            questionRepository.Add(question);

            if (Answer.Count > 0)
            {
        
                for(var i = 0; i < Answer.Count; i++)
                {
                    Choice choice = new Choice
                    {
                        QuestionID = questionRepository.GetLastQuestion().ID,
                        Text = Answer[i],
                        IsCorrect = results.Contains(i.ToString()) ? true: false,
                        Points = model.QuestionTypeID == 1 ? Convert.ToDouble(Percentage[i]) : (results.Contains(i.ToString()) ? 100 : 0)
                    };
                    choiceRepository.Add(choice);
                }
            }
            else
            {
                Choice choice = new Choice
                {
                    QuestionID = questionRepository.GetLastQuestion().ID,
                    Text = "",
                    IsCorrect =  true,
                    Points = model.Points
                };
                choiceRepository.Add(choice);
            };


            SuccessNotification = "Uspješno ste dodali pitanje.";

            return Redirect("/Question/DodajForma?examID=" + model.ExamID);
        }

        [Authorize(Roles = "Admin, Profesor")]
        public IActionResult Delete(int questionID, int examID)
        {
            var questions = questionRepository.GetAll();
            var deletedQuestion = questionRepository.GetById(questionID);

            foreach (var item in questions)
            {
                if (item.ExamID == examID && item.QuestionNumber > deletedQuestion.QuestionNumber)
                    item.QuestionNumber -= 1;
            }

            questionRepository.Delete(questionID);
            SuccessNotification = "Uspješno ste obrisali pitanje.";
            return RedirectToAction("Details", "Exam", new { examID = examID });
        }

        [Authorize(Roles = "Admin, Profesor, Student")]
        public IActionResult Details(int questionID, int examID)
        {
            var question = questionRepository.GetQuestionDetails(questionID);
            ViewBag.ExamID = examID;

            if (question == null)
            {
                ViewBag.ErrorMessage = "Pitanje nije pronađen.";
                return View("_NotFound");
            }
            return View(question);
        }

        [Authorize(Roles = "Admin, Profesor")]
        public IActionResult Edit(int questionID, int examID)
        {
            var question = questionRepository.EditQuestion(questionID);

            if (question == null)
            {
                ViewBag.ErrorMessage = "Pitanje nije pronađeno.";
                return View("_NotFound");
            }

            question.QuestionCategoryList = questionRepository.GetQuestionCategories();

            question.QuestionTypeList.Add(new SelectListItem { Text = "Više ponuđenih više tačnih", Value = ((int)QuestionType.MultipleChoice).ToString() });
            question.QuestionTypeList.Add(new SelectListItem { Text = "Više ponuđenih jedno tačno", Value = ((int)QuestionType.Matching).ToString() });
            question.QuestionTypeList.Add(new SelectListItem { Text = "Esej", Value = ((int)QuestionType.Essay).ToString() });

            return PartialView(question);
        }

        [Authorize(Roles = "Admin, Profesor")]
        public IActionResult SpremiIzmjene(QuestionEditVM m)
        {
            var question = questionRepository.GetById(m.QuestionID);
            if (question == null)
            {
                ViewBag.ErrorMessage = "Pitanje nije pronađeno.";
                return View("_NotFound");
            }
            else
            {
                question.QuestionCategoryID = m.QuestionCategoryID;
                question.QuestionType = m.QuestionType;
                question.Text = m.Text;
                question.Points = m.Points;
      
                questionRepository.Update(question);
                SuccessNotification = "Uspješno ste ažurirali pitanje.";
            }

            return RedirectToAction("Details", "Exam", new { examID = m.ExamID });
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddQuestionCategoryForm()
        {
            return PartialView();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddQuestionCategory(string categoryName)
        {
            QuestionCategory category = new QuestionCategory { CategoryName = categoryName };
            _questionCategoryRepository.Add(category);
            SuccessNotification = "Uspješno ste dodali kategoriju.";

            return RedirectToAction("AdminIndex","Exam");
        }

    }
}

OnlineCourseApp/Views/Question/AddQuestionCategoryForm.cshtml
<form action="/Question/AddQuestionCategory" method="post">
    <div class="form-group">
        <label>Naziv kategorije</label>
        <input type="text" name="categoryName" class="form-control" />
    </div>
    <input type="submit" class="btn btn-outline-primary" value="Sačuvaj">
</form>

OnlineCourseApp/Views/Question/Details.cshtml
@using OnlineCourseApp.Data.Models.Basic
@model QuestionDetailsVM
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
      int examID = ViewBag.ExamID;
}

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="@Url.Action("Details", "Exam", new { examID = examID})">Test</a>
                <i class="fa fa-chevron-right"></i>
            </li>
            <li>
                <span>Detalji pitanja</span>
            </li>
        </ul>
    </div>

    <div class="card card-body">

        <div class="card card-body examDetalji">
            <p>Kateogrija pitanja: <span>   @Model.QuestionCategory</span></p>
            <p>Vrsta pitanja: <span>@Extensions.GetEnumDisplayName(Model.QuestionType)</span></p>
            <p>Bodovi: <span>   @Model.Points</span></p>
            <p>Pitanje: <span>  @Model.Text</span></p>

        </div>

        @if(Model.QuestionType.ToString() != "Essay")
        {
        <table class="table table-bordered table-sm">
            <thead>
                <tr>
                    <td>Odgovor</td>
                    <td>Postotak</td>
                    <td>Tačnost</td>
                    <td>Akcije</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Choises)
                {
                    <tr>
                        <td>@item.Text</td>
                        <td>@item.Points%</td>
                        <td>@item.IsCorrect</td>
                        <td>
                            <a data-url="@Url.Action("Edit","Choice", new { choiceID=item.ChoiceID, examID = examID})" data-container="body" data-modaltitle="Uredi odgovor" class="btn-popup"><i class="fa fa-edit" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Uredi"></i></a>
                            <a href="@Url.Action("Delete", "Choice", new { choiceID = item.ChoiceID ,questionID = Model.QuestionID, examID = examID})"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" title="Obriši"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        }
    </div>

OnlineCourseApp/Views/Question/DodajForma.cshtml
@model QuestionAddVM
@{
    ViewData["Title"] = "Dodaj pitanje";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int examID = ViewBag.ExamID;
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Details", "Exam", new { examID = examID})">Test</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Dodaj pitanje</span>
        </li>
    </ul>
</div>
<div class="card card-body col-9">
    <form asp-action="Dodaj" asp-controller="Question" method="post">
        <input asp-for="ExamID" style="display:none" />

        <div class="form-group">
            <label>Kategorija pitanja</label>
            <select class="form-control" asp-for="@Model.QuestionCategoryID" asp-items="@Model.QuestionCategory">
                <option disabled>Odaberite kategoriju</option>
            </select>
        </div>
        <div class="form-group">
            <label>Tip pitanja</label>
            <select class="form-control" asp-for="@Model.QuestionTypeID" asp-items="@Model.QuestionType" onchange="showButton(this.value)" id="questionType">
                <option disabled>Odaberite tip</option>
            </select>
        </div>

        <div class="form-group">
            <label asp-for="Points">Bodovi</label>
            <input type="number" asp-for="Points" class="form-control" />
            <span asp-validation-for="Points" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label asp-for="Text">Tekst pitanja</label>
            <textarea asp-for="Text" class="form-control"></textarea>
            <span asp-validation-for="Text" class="text-danger"></span>

        </div>

        <div id="ajaxQuestions"></div>
        <input type="button" class="btn btn-outline-info btn-sm" value="Dodaj odgovore" id="addAnswers" onclick="addInput()">
        <input type="submit" class="btn btn-outline-primary" value="Sačuvaj" id="submitQuestion">

    </form>
</div>


<style>
    .divFormGroup {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    #ajaxQuestions label {
        white-space: nowrap;
        margin-right: 15px;
        margin-left: 15px;
        margin-bottom: 0;
    }
     #ajaxQuestions .percentage{
         width:50px;
         margin-left: 15px;
     }
     #submitQuestion{
         margin-right: 0px;
    margin-left: auto;
    display: block;
     }
</style>


@section scripts {
    <script>
        $("#submitQuestion").hide();
        var parentDiv = document.getElementById("ajaxQuestions");

        function showButton(value) {

            $("#ajaxQuestions").empty();
            brojac = 1;
            checkboxBrojac = 0;

            if (value == 3) {
                $("#addAnswers").hide();
                $("#submitQuestion").show();
            }
            else {
                $("#addAnswers").show();
                $("#submitQuestion").hide();
            }
        }

        var brojac = 1;
        var checkboxBrojac = 0;

        function addInput() {
            var div = document.createElement("div");
            div.className = "form-group divFormGroup";

            var label = document.createElement("label");
            label.innerHTML = `Opcija ${brojac++}`;

            var input = document.createElement("input");
            input.className = "form-control";
            input.name = "Answer";


            var check = document.createElement("input");
                check.name = "checkboxes";
                check.value = checkboxBrojac++;
            if ($("#questionType").val() == 1) {
                check.type = 'checkbox';

                var percentage = document.createElement("input");
                percentage.className = "form-control percentage";
                percentage.name = "Percentage";
                percentage.placeholder = "%";
            }
            else {
                check.type = 'radio';
            }
         
            div.appendChild(check);
            div.appendChild(label);
            div.appendChild(input);
           if ($("#questionType").val() == 1) {
            div.appendChild(percentage);
            }


            parentDiv.appendChild(div);

            $("#submitQuestion").show();
        }

    </script>
}

OnlineCourseApp/Views/Question/Edit.cshtml
@model QuestionEditVM
@{
    ViewData["Title"] = "Uredi pitanje";
}

    <div class="col-md-12">
        <form asp-action="SpremiIzmjene" asp-controller="Question" method="post">
            <input asp-for="QuestionID" hidden />
            <input asp-for="ExamID" hidden />
            <div class="form-group">
                <label>Kategorija pitanja</label>
                <select class="form-control" asp-for="@Model.QuestionCategoryID" asp-items="@Model.QuestionCategoryList">
                    <option disabled>Odaberite kategoriju</option>
                </select>
            </div>
            <div class="form-group">
                <label>Tip pitanja</label>
                <select class="form-control" asp-for="@Model.QuestionType" asp-items="@Model.QuestionTypeList">
                    <option disabled>Odaberite tip</option>
                </select>
            </div>

            <div class="form-group">
                <label asp-for="Points">Bodovi</label>
                <input type="number" asp-for="Points" class="form-control" />
                <span asp-validation-for="Points" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Text">Tekst pitanja</label>
                <textarea asp-for="Text" class="form-control"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>

            </div>

            <input type="submit" class="btn btn-outline-primary" value="Sačuvaj">

        </form>
        </div>