OnlineCourseApp/Controllers/CourseSectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.Models.Basic;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class CourseSectionController : NotificationsController
    {
        private ICourseSectionRepository courseSectionRepository;
        private ICourseSectionRepository2 courseSectionRepository2;
        private ICourseTypeRepository courseTypeRepository;
        private ICourseTypeRepository2 courseTypeRepository2;

        public CourseSectionController(ICourseSectionRepository courseSectionRepository,
                                      ICourseSectionRepository2 courseSectionRepository2,
                                      ICourseTypeRepository courseTypeRepository,
                                      ICourseTypeRepository2 courseTypeRepository2)
        {
            this.courseSectionRepository = courseSectionRepository;
            this.courseSectionRepository2 = courseSectionRepository2;
            this.courseTypeRepository = courseTypeRepository;
            this.courseTypeRepository2 = courseTypeRepository2;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult DodajForma()
        {

            ViewData["courseType"] = courseTypeRepository2.GetCourseTypeList();
            ViewData["courseParent"] = courseSectionRepository2.GetCourseSectionList();
            CourseSectionAddVM Model = new CourseSectionAddVM();
            return PartialView(Model);

        }
        public IActionResult Dodaj(CourseSectionAddVM cs)
        {
            CourseSection courseSection = new CourseSection
            {
                Name=cs.Name,
                Description = cs.Description,
                CourseTypeID = cs.CourseTypeID,
                CourseParentID=cs.CourseParentID

            };
            courseSectionRepository.Add(courseSection);
            SuccessNotification = "Uspješno ste dodali sekciju kursa.";

            return Redirect("/CourseSection/Prikaz");
        }
        public IActionResult Prikaz()
        {
            var cs = courseSectionRepository.GetAllCourseSections();
            return View(cs);
        }

        public IActionResult Obrisi(int CourseSectionID)
        {
            courseSectionRepository.Delete(CourseSectionID);
            SuccessNotification = "Uspješno ste obrisali sekciju kursa.";

            return Redirect(url: "/CourseSection/Prikaz");
        }

        public IActionResult Uredi(int CourseSectionID)
        {
            ViewData["courseType"] = courseTypeRepository2.GetCourseTypeList();
            ViewData["courseParent"] = courseSectionRepository2.GetCourseSectionList();
            var courseSection = courseSectionRepository.EditCourseSection(CourseSectionID);

            if (courseSection == null)
            {
                ViewBag.ErrorMessage = "Sekcija kursa nije pronađena";
                return View("_NotFound");
            }

            return PartialView(courseSection);
        }

        public IActionResult SpremiIzmjene(CourseSectionEditVM model)
        {

            var courseSection = courseSectionRepository.GetById(model.CourseSectionID);
            if (courseSection == null)
            {
                ViewBag.ErrorMessage = "Sekcija kursa nije pronađena";
                return View("_NotFound");
            }
            else
            {
                courseSection.Name = model.Name;
                courseSection.Description = model.Description;
                courseSection.CourseTypeID = model.CourseTypeID;
                courseSection.CourseParentID = model.CourseParentID;

                courseSectionRepository.Update(courseSection);
                SuccessNotification = "Uspješno ste izmjenili odabranu sekciju.";
            }

            return RedirectToAction("Prikaz", "CourseSection");
        }

    }
}

OnlineCourseApp/Controllers/CourseTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.Models.Basic;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class CourseTypeController : Controller
    {
        private ICourseTypeRepository courseTypeRepository;
        public CourseTypeController(ICourseTypeRepository courseTypeRepository)
        { this.courseTypeRepository = courseTypeRepository; }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DodajForma()
        {
            CourseTypeVM Model = new CourseTypeVM();
            return PartialView(Model);

        }
        public IActionResult Dodaj(CourseTypeVM ct)
        {
            CourseType courseType = new CourseType
            {
                Name=ct.Name,
                Description = ct.Description
            };
            courseTypeRepository.Add(courseType);

            return Redirect("/CourseType/Prikaz");
        }

        public IActionResult Prikaz()
        {
            var courseTypes = courseTypeRepository.GetAllCourseTypes();
            return View(courseTypes);
        }

        public IActionResult Obrisi(int courseTypeID)
        {
            courseTypeRepository.Delete(courseTypeID);

            return Redirect(url: "/CourseType/Prikaz");
        }
    }
}

OnlineCourseApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.DataRepository.IDataRepository;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;
using OnlineCourseApp.Enums;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {
        private IAnnouncementRepository _announcementRepository;
        private readonly UserManager<AppUser> _userManager;
        private ICourseRepository _courseRepository;
        private IStudentRepository _studentRepository;
        public DashboardController(IAnnouncementRepository announcementRepository, ICourseRepository courseRepository, UserManager<AppUser> userManager, IStudentRepository studentRepository)
        {
            _announcementRepository = announcementRepository;
            _courseRepository = courseRepository;
            _userManager = userManager;
            _studentRepository = studentRepository;
        }
        public IActionResult Home(string permission = null)
        {
            HttpContext.Session.SetString("ref", "dashboard");

            if (permission != null || Permission != null)
            {
                if (permission == null && Permission != null)
                    permission = Permission;
                
                Permission = permission;
                if (User.IsInRole(permission))
                {
                    if (permission == "Admin")
                    {
                        return View($"{permission}Home", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncementsForAdmin() });

                    }
                    AnnouncementFilterType x = permission == "Student" ? AnnouncementFilterType.AllStudents : AnnouncementFilterType.AllProfessors;
                    return View($"{permission}Home", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(x), Courses = _courseRepository.GetAllCourses() });
                }
            }
            if (User.IsInRole("Admin"))
            {
                Permission = "Admin";
                return View("AdminHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncementsForAdmin() });
            }

            else if (User.IsInRole("Profesor"))
            {
                Permission = "Profesor";
                return View("ProfesorHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(AnnouncementFilterType.AllProfessors) });
            }

            else if (User.IsInRole("Student"))
            {
                string userID = _userManager.GetUserId(User);
                int studentID = _studentRepository.GetCurrentStudentId(int.Parse(userID));
                Permission = "Student";
                return View("StudentHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(AnnouncementFilterType.AllStudents), Courses = _courseRepository.GetNotAppliedCourses(studentID) });
            }
            else
                return RedirectToAction("Login", "Account");
        }
    }

}

OnlineCourseApp/Views/CourseSection/DodajForma.cshtml
@model CourseSectionAddVM
@{
    var courseType = (List<SelectListItem>)ViewData["courseType"];
    var courseParent = (List<SelectListItem>)ViewData["courseParent"];
}

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Dodaj sekciju kursa</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form asp-action="Dodaj" asp-controller="CourseSection" method="post" id="forma">
            <div class="modal-body">
                <input asp-for="CourseSectionID" style="display:none" />
                <div class="form-group">
                    <label>Naziv sekcije</label>
                    <input asp-for="Name" class="form-control" name="Name" id="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label>Opis</label>
                    <input asp-for="Description" class="form-control" name="Description" id="Opis" />
                    <span asp-validation-for="Description" class="text-danger"></span>

                </div>

                <div class="form-group">
                    <label>Tip kursa</label>
                    <div style="display:flex">
                    <select asp-for="CourseTypeID" asp-items="courseType" class="form-control">
                        <option disabled>(Odaberite tip kursa)</option>
                    </select>
                <a href="@Url.Action("Prikaz","CourseType")" class="cursor-pointer btn btn-primary btn-popup" style="margin-left:1rem">+</a>         
                    </div>
                    <span asp-validation-for="CourseTypeID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Glavna oblast</label>
                    <select asp-for="CourseParentID" asp-items="courseParent" class="form-control">
                        <option>(Odaberite glavnu oblast)</option>
                    </select>
                    <span asp-validation-for="CourseParentID" class="text-danger"></span>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zatvori</button>
                    <input type="submit" class="btn btn-primary" value="Sačuvaj" id="submit">
                </div>
            </div>
        </form>
    </div>
</div>

OnlineCourseApp/Views/CourseSection/Prikaz.cshtml
@model List<CourseSectionPreviewVM>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Home", "Dashboard")">Radna ploča</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Kursevi</span>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-3">

        </div>
        <div class="col-md-3">

        </div>

        <div class="col-md-3">
            <button type="button" class="btn btn-primary" id="btn-popup3"><i class="fa fa-plus-circle"></i> Dodaj sekciju</button>

        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <table class="table table-striped table-bordered" style="background:white;">
            <thead>
                <tr>
                    <th scope="col">Oblast kursa</th>
                    <th scope="col">Opis</th>
                    <th scope="col">Tip kursa</th>
                    <th scope="col">Glavna oblast</th>
                    <th scope="col">Akcije</th>
                </tr>
            </thead>
            <tbody>
                @foreach (CourseSectionPreviewVM x in Model)
                {

                    @if (x.Name != null)
                    {
                        <tr>
                            <td>  @x.Name </td>
                            <td>  @x.Description </td>
                            <td>  @x.CourseType </td>
                            <td>  @x.CourseParent </td>
                            <td style="display: flex; align-items: center; justify-content: space-evenly;">
                                <a href="@Url.Action("Prikaz","Course", new { courseSectionID=x.CourseSectionID})" class="btn btn-outline-primary btn-sm" style="color:#007bff;">Kursevi</a>
                                <a class="btn-popup" data-container="body" data-modaltitle="Uredi sekciju kursa" data-url="@Url.Action("Uredi","CourseSection",new { CourseSectionID=x.CourseSectionID})"> <i class="fa fa-edit"></i> </a>
                                <a href="/CourseSection/Obrisi?CourseSectionID=@x.CourseSectionID"> <i class="fa fa-trash-o"></i> </a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-url="@Url.Action("DodajForma","CourseSection")" style="z-index: 1400;">
</div>
<div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-url="@Url.Action("DodajForma","CourseType")">
</div>

@section Scripts {
    <script type="text/javascript">

                $(document).ready(function () {

                    $("#btn-popup3").click(function () {
                        event.preventDefault();
                        var url = $("#exampleModalCenter").data('url');
                        jQuery.get(url, function (data) {

                            $("#exampleModalCenter").html(data);
                            $("#exampleModalCenter").modal('show');

                        })
                    })
                });
                $(document).ready(function () {
                    $("#btn-popup2").click(function () {
                        event.preventDefault();
                        var url = $("#exampleModalCenter2").data('url');
                        jQuery.get(url, function (data) {

                            $("#exampleModalCenter2").html(data);
                            $("#exampleModalCenter2").modal('show');


                        })
                    })
                });

    </script>
}

<style>
    label {
        margin-bottom: 0px;
    }

    .container-fluid {
        padding: 15px;
        background: white;
        margin-bottom: 25px;
        border: 1px solid #dee2e6;
        border-radius: 10px;
    }

    #btn-popup3 {
        width: 100%;
    }
    .btn-outline-primary:hover{
        color:white!important;
    }
</style>

OnlineCourseApp/Views/CourseSection/Uredi.cshtml
@model CourseSectionEditVM
@{
    var courseType = (List<SelectListItem>)ViewData["courseType"];
    var courseParent = (List<SelectListItem>)ViewData["courseParent"];
}

<div class="col-md-12">
    <form asp-controller="CourseSection" asp-action="SpremiIzmjene" method="post">
        <div class="form-group" hidden>
            <label asp-for="CourseSectionID"></label>
            <input asp-for="CourseSectionID" class="form-control" readonly />
        </div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" autocomplete="off" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" autocomplete="off" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CourseTypeID"></label>
            <select asp-for="CourseTypeID" asp-items="courseType" class="form-control">
                <option disabled>(Odaberite tip kursa)</option>
            </select>
            <span asp-validation-for="CourseTypeID" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CourseParentID"></label>
            <select asp-for="CourseParentID" asp-items="courseParent" class="form-control">
                <option>(Odaberite glavnu oblast)</option>
            </select>
            <span asp-validation-for="CourseParentID" class="text-danger"></span>
        </div>


        <div class="form-group text-center">
            <input type="submit" style="width:100%" class="btn btn-primary" value="Sačuvaj" id="submit">
        </div>
    </form>
</div>