OnlineCourseApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.DataRepository.IDataRepository;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.Models.Basic;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class CourseController : NotificationsController
    {
        private ICourseRepository courseRepository;
        private ICourseSectionRepository2 courseSectionRepository2;
        private IDocumentShareRepository documentShareRepository;
        private readonly UserManager<AppUser> _userManager;

        public CourseController(UserManager<AppUser> userManager, ICourseRepository courseRepository, ICourseSectionRepository2 courseSectionRepository2,
                                IDocumentShareRepository documentShareRepository)
        {
            _userManager = userManager;
            this.courseRepository = courseRepository;
            this.courseSectionRepository2 = courseSectionRepository2;
            this.documentShareRepository = documentShareRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Prikaz(int courseSectionID)
        {
            var courses = courseRepository.GetCoursesBasedOnSection(courseSectionID);
            return View(courses);
        }
        public IActionResult CourseApplications()
        {
            var courses = courseRepository.GetAllCourses();
            return View(courses);
        }
        public IActionResult DodajForma()
        {

            ViewData["courseSections"] = courseSectionRepository2.GetCourseSectionList();
            CourseAddVM Model = new CourseAddVM();
            return PartialView(Model);

        }
        public async Task<IActionResult> Dodaj(CourseAddVM c)
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            
            Course course = new Course
            {
                CourseName =c.CourseName,
                Start =c.Start,
                End = c.End,
                Notes= c.Notes,
                ProfessorId = user.Id,
                CourseSectionID = c.CourseSectionID,  
                EnableCourseSessions = c.EnableCourseSessions,
                EnableVideoRecording = c.EnableVideoRecording

    };
            courseRepository.Add(course);
            SuccessNotification = "Uspješno ste dodali kurs.";
            return RedirectToAction("GetCoursesByProfessor", "Course");
        }

    
        public IActionResult EditCourse(int courseID)
        {
            ViewData["courseSections"] = courseSectionRepository2.GetCourseSectionList();
            var course = courseRepository.GetById(courseID);

            if (course == null)
            {
                ViewBag.ErrorMessage = "Kurs nije pronađen";
                return View("_NotFound");
            }

            CourseEditVM courseVM = new CourseEditVM
            {
                  CourseID =course.ID,
                  CourseName =course.CourseName,
                  Start =course.Start,
                  End =course.End,
                  Notes =course.Notes,
                  CourseSectionID = course.CourseSectionID,
                  EnableCourseSessions =course.EnableCourseSessions,
                  EnableVideoRecording  = course.EnableVideoRecording
             };
           
            return PartialView(courseVM);
        }
        public IActionResult SaveEditCourse(CourseEditVM c)
        {
            var course = courseRepository.GetById(c.CourseID);
            if (course == null)
            {
                ViewBag.ErrorMessage = "Kurs nije pronađen";
                return View("_NotFound");
            }
            else
            {
                course.CourseName = c.CourseName;
                course.Start = c.Start;
                course.End = c.End;
                course.Notes = c.Notes;
                course.CourseSectionID = c.CourseSectionID;
                course.EnableCourseSessions = c.EnableCourseSessions;
                course.EnableVideoRecording = c.EnableVideoRecording;

                courseRepository.Update(course);
                SuccessNotification = "Uspješno ste ažurirali kurs.";
            }
            return RedirectToAction("GetCoursesByProfessor", "Course");
        }


        public IActionResult Obrisi(int CourseID)
        {
            courseRepository.Delete(CourseID);
            SuccessNotification = "Uspješno ste obrisali kurs.";
            return RedirectToAction("GetCoursesByProfessor", "Course");
        }

        public async Task<IActionResult> GetCoursesByProfessor()
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);

            var courses = courseRepository.GetAllCourses().Where(c => c.ProfessorId == user.Id).ToList();
            return View("ProfessorCourses", courses);
        }

        public async Task<IActionResult> Detalji(int courseID)
        {
            var course = courseRepository.GetCoursesById(courseID);
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);

            if (course == null)
            {
                ViewBag.ErrorMessage = "Kurs nije pronađen";
                return View("_NotFound");
            }
            ViewData["Documents"] = documentShareRepository.GetDocumentByUserAndCourse(user.Id, courseID); 
            return View(course);
        }

    }
}

OnlineCourseApp/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.DataRepository.IDataRepository;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.RepositoryInterfaces;
using OnlineCourseApp.Data.ViewModels;
using OnlineCourseApp.Enums;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {
        private IAnnouncementRepository _announcementRepository;
        private readonly UserManager<AppUser> _userManager;
        private ICourseRepository _courseRepository;
        private IStudentRepository _studentRepository;
        public DashboardController(IAnnouncementRepository announcementRepository, ICourseRepository courseRepository, UserManager<AppUser> userManager, IStudentRepository studentRepository)
        {
            _announcementRepository = announcementRepository;
            _courseRepository = courseRepository;
            _userManager = userManager;
            _studentRepository = studentRepository;
        }
        public IActionResult Home(string permission = null)
        {
            HttpContext.Session.SetString("ref", "dashboard");

            if (permission != null || Permission != null)
            {
                if (permission == null && Permission != null)
                    permission = Permission;
                
                Permission = permission;
                if (User.IsInRole(permission))
                {
                    if (permission == "Admin")
                    {
                        return View($"{permission}Home", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncementsForAdmin() });

                    }
                    AnnouncementFilterType x = permission == "Student" ? AnnouncementFilterType.AllStudents : AnnouncementFilterType.AllProfessors;
                    return View($"{permission}Home", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(x), Courses = _courseRepository.GetAllCourses() });
                }
            }
            if (User.IsInRole("Admin"))
            {
                Permission = "Admin";
                return View("AdminHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncementsForAdmin() });
            }

            else if (User.IsInRole("Profesor"))
            {
                Permission = "Profesor";
                return View("ProfesorHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(AnnouncementFilterType.AllProfessors) });
            }

            else if (User.IsInRole("Student"))
            {
                string userID = _userManager.GetUserId(User);
                int studentID = _studentRepository.GetCurrentStudentId(int.Parse(userID));
                Permission = "Student";
                return View("StudentHome", new DashboardVM { Announcements = _announcementRepository.GetLastAnnouncements(AnnouncementFilterType.AllStudents), Courses = _courseRepository.GetNotAppliedCourses(studentID) });
            }
            else
                return RedirectToAction("Login", "Account");
        }
    }

}

OnlineCourseApp/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineCourseApp.Data.DataRepository.IDataRepository;
using OnlineCourseApp.Data.Models;
using OnlineCourseApp.Data.Models.Basic;

namespace OnlineCourseApp.Controllers
{
    [Authorize]
    public class DocumentController : NotificationsController
    {
        private IDocumentRepository documentRepository;
        private IDocumentShareRepository documentShareRepository;
        private readonly UserManager<AppUser> _userManager;

        public DocumentController(UserManager<AppUser> userManager, IDocumentRepository documentRepository, IDocumentShareRepository documentShareRepository)
        {
            _userManager = userManager;
            this.documentRepository = documentRepository;
            this.documentShareRepository = documentShareRepository;
        }
        public async Task<IActionResult> Upload(IFormFile file, int courseID)
        {
            if (file != null)
            {
                if (file.Length > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var fileExtension = Path.GetExtension(fileName);
                    var contentType = file.ContentType;
                    var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                    string folder = "wwwroot/uploads/";
                    bool exists = Directory.Exists(folder);
                    if (!exists)
                        Directory.CreateDirectory(folder);

                    var path = Path.Combine( Directory.GetCurrentDirectory(), folder, newFileName);

                    AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
                    Document doc = new Document
                    {
                        FileOldName = fileName,
                        FileName = newFileName,
                        FileExtension = fileExtension,
                        FilePath = newFileName,
                        UploadDate =DateTime.Now,
                        ContentType =contentType,
                        DocumentOwnerID = user.Id
                    };
               

                    using (var stream = new FileStream(folder + newFileName, FileMode.Create))
                    {
                        file.CopyTo(stream);
                        stream.Close();
                    }

                    documentRepository.Add(doc);
                  
                    DocumentShare docShare = new DocumentShare
                    {
                        CourseID = courseID,
                        DocumentID = documentRepository.GetLastUploaded().ID
                    };
                    documentShareRepository.Add(docShare);
                    SuccessNotification = "Uspješno ste dodali dokument.";

                }
            }
                                   
            return RedirectToAction("Detalji", "Course", new { courseID = courseID });
        }

        public IActionResult Delete(int documentID, int courseID)
        {
            Document doc = documentRepository.GetById(documentID);
            string fullPath = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/uploads/" + doc.FileName);

            //System.IO.File.Create(fullPath).Close();

            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                
                documentRepository.Delete(documentID);
               SuccessNotification = "Uspješno ste obrisali dokument.";
            }
            else
            {
                ErrorNotification = "Greška prilikom brisanja dokumenta.";
            }
            return RedirectToAction("Detalji", "Course", new { courseID = courseID });
        }

        public async Task<IActionResult> DownloadFile(int documentID)
        {
            Document doc = documentRepository.GetById(documentID);
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads/", doc.FileName);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
                stream.Close();
            }
            memory.Position = 0;
            return File(memory, "application/octet-stream", doc.FileName);
        }
    }
}

OnlineCourseApp/Views/Course/CourseApplications.cshtml
@model List<CourseVM>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Home", "Dashboard")">Radna ploča</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Prijave</span>
        </li>
    </ul>
</div>
<div class="card">
    <div class="card-body">
        <div class="row">

            @foreach (CourseVM x in Model)
            {
                @if (x.CourseName != null)
                {

                    <div class="mt-4 col-sm-4">
                        <div class="project-box">
                            <h6 style="margin-bottom: 0.1rem;">@x.CourseName</h6>
                            <div class="media" style="border-bottom: 1px solid rgb(244, 244, 244);">
                                <div class="media-body" style="padding-bottom: 0.5rem;">
                                    <div style="margin-bottom: 1rem;">
                                        <p style="font-size: 0.8rem;">@x.CourseSection</p>
                                    </div>
                                    <div style=" margin-bottom: 1rem;">
                                        <p>@x.Notes</p>
                                    </div>
                                    <p class="f-12 date" style="text-align: right;">@x.Start.ToShortDateString() - @x.End.ToShortDateString()</p>
                                </div>
                            </div>
                            <div class="row" style=" margin-top: 20px;">
                                <div class="col-sm-6 col-3">
                                    <a class="btn btn-outline-primary btn-block btn-sm" style="padding: 0.375rem 0.75rem; color: #007bff;" href="@Url.Action("CourseParticipantsList","CourseParticipant", new { courseID = x.CourseID})">Prijavljeni</a>
                                </div>
                                <div class="col-sm-6 col-3">
                                    <a class="btn btn-outline-danger btn-block btn-sm" style="padding: 0.375rem 0.75rem;" href="/Course/Obrisi?CourseID=@x.CourseID">Obriši</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }

        </div>







        @*<table class="table table-striped table-bordered" style="background:white;">
                <tr>
                    <th scope="col">Naziv kursa</th>
                    <th scope="col">Početak</th>
                    <th scope="col">Kraj</th>
                    <th scope="col">Bilješka</th>
                    <th scope="col">Oblast kursa</th>
                    <th scope="col"></th>
                    <th scope="col">Akcija</th>
                </tr>
                @foreach (CourseVM x in Model)
                {
                    @if (x.CourseName != null)
                    {
                        var id = $"multiCollapse{x.CourseID}";
                        <tr>
                            <td>  @x.CourseName </td>
                            <td>  @x.Start.ToShortDateString() </td>
                            <td>  @x.End.ToShortDateString() </td>
                            <td>  @x.Notes </td>
                            <td>  @x.CourseSection </td>
                            <td>
                                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#@id" aria-expanded="true" aria-controls="@id">Prijavljeni</button>
                            </td>
                            <td>
                                <a href="/Course/Obrisi?CourseID=@x.CourseID"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>

                        <tr class="collapse" id="@id">

                            <td colspan="8">

                                @if (x.CourseParticipants.Count > 0)
                                {
                                    <table>
                                        <tr>
                                            <td>ID broj</td>
                                            <td>Ime</td>
                                            <td>Prezime</td>
                                            <td>Email</td>
                                        </tr>
                                        @foreach (var item in x.CourseParticipants)
                                        {
                                            <tr>
                                                <td>@item.StudentIDNumber</td>
                                                <td>@item.FirstName</td>
                                                <td>@item.LastName</td>
                                                <td>@item.Email</td>
                                            </tr>
                                        }
                                    </table>
                                }
                            </td>

                        </tr>
                    }
                }
            </table>*@
    </div>
</div>


<style>
    label {
        margin-bottom: 0px;
    }

    .container-fluid {
        padding: 15px;
        background: white;
        margin-bottom: 25px;
        border: 1px solid #dee2e6;
        border-radius: 10px;
    }

    .btn-popup {
        width: 100%;
    }

    .project-box {
        border: 1px solid #efefef;
        border-radius: 5px;
        padding: 25px;
        background-color: #fff;
    }

    .btn-outline-primary:hover {
        color: white !important;
    }
</style>

OnlineCourseApp/Views/Course/Detalji.cshtml
@model CourseDetaljiVM
@{
    ViewData["Title"] = "Detalji";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<DocumentPreviewVM> documents = (List<DocumentPreviewVM>)ViewData["Documents"];
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("GetCoursesByProfessor", "Course")">Kursevi</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Detalji</span>
        </li>
    </ul>
</div>

<div class=" courseDetalji">
    <div class="card card-body" style="display:flex; flex-direction: row; justify-content: space-between; align-items: flex-end; padding-bottom: 0rem;">
        <div>
            <label>Naziv kursa</label>
            <p style="margin-bottom: 0.3rem;">@Model.CourseName</p>
            <p style="font-size:0.9rem;">(@Model.CourseSection)</p>

        </div>
        <div>
            <label>Trajanje</label>
            <p> @Model.Start.ToShortDateString() -  @Model.End.ToShortDateString()</p>
        </div>

    </div>

    <div style="width:60%" class="card">
        <div class="card-body">
            <label style="margin-bottom:0.5rem;">Lista prijavljenih</label>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Ime i prezime</th>
                        <th scope="col">Email</th>
                        <th scope="col">Akcija</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.CourseParticipants)
                    {
                        <tr>
                            <td>@item.FirstName @item.LastName</td>
                            <td>@item.Email</td>
                            <td><a  href="@Url.Action("DeleteParticipant","CourseParticipant", new{ paxID = item.CoursePaxID, courseID = Model.CourseID })"><i class="fa fa-trash-o"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>


    </div>


    <div class="card uploadDocument">
        <div class="card-body">
            <label style="margin-bottom:0.5rem;">Dokumenti</label>
            <table class="table table-sm table-hover">

                <tbody>
                    @foreach (var item in documents)
                    {
                        <tr data-toggle="tooltip" data-placement="top" title="Download" onclick="location.href = '@(Url.Action("DownloadFile","Document",new {documentID = item.DocumentID}))'">
                            <td style="text-align: left;">@item.FileName</td>
                            <td> <a href="@Url.Action("Delete","Document", new { documentID=item.DocumentID, courseID = Model.CourseID})"><i class="fa fa-trash-o"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <form method="post" enctype="multipart/form-data" action="/Document/Upload">
                <div style="  float:right; margin-top:1rem; display: flex; align-items: center;">
                    <input name="courseID" style="display:none" value="@Model.CourseID" />
                    <input type="file" name="file" accept=".pdf" />
                    <input type="submit" class="btn btn-primary btn-sm" style="width:auto; margin-left: 0.5rem; color:#fff" value="Upload" />
                </div>
            </form>
        </div>


    </div>

</div>


<style>
    .courseDetalji label {
        font-weight: bold;
        font-size: 0.9rem;
        margin-bottom: 0.04rem;
        letter-spacing: 0.07rem;
    }

    .courseDetalji p {
        font-size: 1rem;
        color: #0c1a5d;
    }

    .uploadDocument input {
        border: 1.5px solid #088ee4;
        border-radius: 5px;
        padding: 5px;
        color: #088ee4;
    }

        .uploadDocument input::-webkit-file-upload-button {
            color: #fff;
            background: #088ee4;
            border-radius: 5px;
            border: none;
            padding: 2px 6px;
            outline: none;
        }

            .uploadDocument input::-webkit-file-upload-button:hover {
                cursor: pointer;
                background: #0856e4;
            }

    .table-hover {
        cursor: pointer;
    }
</style>

OnlineCourseApp/Views/Course/DodajForma.cshtml
@model CourseAddVM
@{
    var courseSections = (List<SelectListItem>)ViewData["courseSections"];
}

        <form asp-action="Dodaj" method="post" id="forma">
            <div class="modal-body">
                <input asp-for="CourseID" style="display:none" />
                <div class="form-group">
                    <label>Naziv kursa</label>
                    <input asp-for="CourseName" type="text" class="form-control" name="CourseName" id="nazivKursa" />
                    <span asp-validation-for="CourseName" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label>Početak kursa</label>
                            <input asp-for="Start" type="date" class="form-control" name="Start" id="pocetakKrsa" value="@DateTime.Now"/>
                            <span asp-validation-for="Start" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label>Kraj kursa</label>
                            <input asp-for="End" type="date" class="form-control" name="End" id="krajKursa" />
                            <span asp-validation-for="End" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="form-group">
                    <label>Oblasti kursa</label>
                    <select asp-for="CourseSectionID" asp-items="courseSections" class="form-control">
                        <option disabled>(Odaberite oblast kursa)</option>
                    </select>
                    <span asp-validation-for="CourseSectionID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div style="display:flex; align-items:center">
                        <input asp-for="EnableCourseSessions" type="checkbox" name="EnableCourseSessions" id="sesijeKursa" />
                        <label style="margin-left:20px;">Omogući sesije kursa</label>
                    </div>
                    <span asp-validation-for="EnableCourseSessions" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div style="display:flex; align-items:center">
                        <input asp-for="EnableVideoRecording" type="checkbox" name="EnableVideoRecording" id="snimanjeKursa" />
                        <label style="margin-left:20px;">Omogući video snimanje</label>
                    </div>
                    <span asp-validation-for="EnableVideoRecording" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Bilješka</label>
                    <textarea asp-for="Notes" type="text" class="form-control" name="Notes" id="biljeska"></textarea>
                    <span asp-validation-for="Notes" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Sačuvaj" id="submit">
                </div>
            </div>
        </form>


<style>
    .error {
        color: darkred;
        display: block;
    }
</style>

OnlineCourseApp/Views/Course/ProfessorCourses.cshtml
@model List<CourseVM>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Home", "Dashboard")">Radna ploča</a>
            <i class="fa fa-chevron-right"></i>
        </li>
        <li>
            <span>Kursevi</span>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-3">

        </div>
        <div class="col-md-3">

        </div>

        <div class="col-md-3">
            <button type="button" class="btn btn-primary btn-popup" data-container="body" data-modaltitle="Dodaj kurs" data-url="@Url.Action("DodajForma","Course")"><i class="fa fa-plus-circle"></i> Dodaj kurs</button>

        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="row">

            @foreach (CourseVM x in Model)
            {
                @if (x.CourseName != null)
                {
                   
                    <div class="mt-4 col-sm-4">
                        <div class="project-box">
                            <h6>@x.CourseName</h6>
                            <div class="media" style="border-bottom: 1px solid rgb(244, 244, 244);">
                                <div class="media-body" style="padding-bottom: 0.5rem;">
                                    <div style="margin-bottom: 1.55rem;">
                                        <p>@x.CourseSection</p>
                                    </div>
                                    <div style=" margin-bottom: 1.55rem;">
                                        <p>@x.Notes</p>
                                    </div>
                                    <p class="f-12 date" style="text-align: right;">@x.Start.ToShortDateString() - @x.End.ToShortDateString()</p>
                                    <p class="f-12 date" style="text-align: right; color: #007bff;"><a style=" cursor:pointer;" href="@Url.Action("Detalji","Course",new { courseID=x.CourseID})">Detalji</a></p>
                                </div>
                            </div>
                            <div class="row" style="    margin-top: 20px;">
                                <div class="col-sm-6 col-3">
                                    <a data-container="body" data-modaltitle="Uredi kurs" data-url="@Url.Action("EditCourse","Course",new { courseID=x.CourseID})" class=" btn-popup btn btn-outline-primary btn-block btn-sm" style="padding: 0.375rem 0.75rem; color: #007bff;">Ažuriraj</a>
                                </div>
                                <div class="col-sm-6 col-3">
                                    <a class="btn btn-outline-danger btn-block btn-sm" style="padding: 0.375rem 0.75rem;" href="/Course/Obrisi?CourseID=@x.CourseID">Obriši</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }

        </div>
    </div>
</div>








<style>
    label {
        margin-bottom: 0px;
    }

    .container-fluid {
        padding: 15px;
        background: white;
        margin-bottom: 25px;
        border: 1px solid #dee2e6;
        border-radius: 10px;
    }

    .btn-popup {
        width: 100%;
    }

    .project-box {
        border: 1px solid #efefef;
        border-radius: 5px;
        padding: 30px;
        background-color: #fff;
    }
    .btn-outline-primary:hover{
        color:white!important;
    }
</style>